language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - bash <(wget -q -O- neuro.debian.net/_files/neurodebian-travis.sh)
  - sudo apt-get install -qq python-dev python-setuptools python-numpy python-scipy python-matplotlib python-lxml python-sqlalchemy python-suds gfortran
  - sudo apt-get install -qq python-statsmodels python-joblib
  - pip install future
  # XXX: At the moment qopen is working only with obspy master
  - pip install --allow-external obspy --allow-insecure obspy obspy==dev
  - pip freeze

install:
  - pip install .
script:
  - qopen-runtests
after_success:
notifications:
    email: false