language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - lsb_release -a # get info on the operating system
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-dev python-setuptools python-numpy python-scipy python-matplotlib python-lxml python-sqlalchemy python-suds gfortran
  - wget -O- http://neuro.debian.net/lists/precise.us-ca.libre | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
  - sudo apt-key adv --recv-keys --keyserver hkp://pgp.mit.edu:80 0xA5D32F012649A5A9
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-statsmodels python-joblib
  - pip install future
  # XXX: At the moment qopen is working only with obspy master
  - pip install --allow-external obspy --allow-insecure obspy obspy==dev
  - pip freeze

install:
  - pip install .
script:
  - qopen-runtests
after_success:
notifications:
    email: false